name: Obtain Next Wheel Version
description: Obtain next wheel version to use. Defaults to 1.0.

inputs:
  published_wheel_version_file_url:
    description: The url of the file containing the name of the file containing the latest published wheel version

outputs:
  next_version:
    description: The next version to use for publishing Python wheel
    value: ${{ steps.next-version.outputs.next_version }}

runs:
  using: "composite"
  steps:
    - id: next-version
      run: |
        url=${{ inputs.published_wheel_version_file_url }}

        # Return default version if version file doesn't exist
        if ! wget -q $url
        then
          echo "::set-output name=next_version::1.0"
          exit 0
        fi

        # Read version from url
        version=$(curl $url)

        # Bump the version. See https://stackoverflow.com/questions/4485399/how-can-i-bump-a-version-number-using-bash
        next_version=$(echo $version | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')

        # Set next version as output variable
        echo "::set-output name=next_version::$next_version"
      shell: bash
