# Configuration of Python unit test code coverage thresholds

[coverage-threshold]
# OBS: This should be 80, but that requirement isn't satisfied at the time of creation of this (it is 73ish)
# This is why threshold is set to 73 to prevent it from blocking PR's
combined_coverage_min = 73
line_coverage_min = 73

    [coverage-threshold.modules."geh_stream/"]
    combined_coverage_min = 73
    line_coverage_min = 73

    [coverage-threshold.modules."geh_stream/*/"]
    combined_coverage_min = 73
    line_coverage_min = 73
