name: 'Read Pipeline Configuration File'
description: 'Reads pipeline configuration file based on last section of branch name and sets environemnt variables. Note: expects Python to be installed on a runner.'
inputs:
  config-file:
    description: 'Configuration file to use'
    required: false
runs:
  using: "composite"
  steps: 
    - run: |
        if [ -z ${{ inputs.config-file }} ]
        then
          IFS='/' read -ra ADDR <<< "${GITHUB_REF#refs/heads/}"
          if test -f "./build/configurations/${ADDR[-1]}.json";
          then
            filename="${ADDR[-1]}.json";
          else
            filename="main.json";
          fi;
        else
         filename=${{ inputs.config-file }}
        fi
        
        file_content=$(cat "./build/configurations/${filename}")
        env_name=$(echo $file_content | python3 -c "import sys, json; print(json.load(sys.stdin)['env_name'])")
        organisation_name=$(echo $file_content | python3 -c "import sys, json; print(json.load(sys.stdin)['organisation_name'])")
        resource_group_name=$(echo $file_content | python3 -c "import sys, json; print(json.load(sys.stdin)['resource_group_name'])")
        github_secret_name_spn_secret=$(echo $file_content | python3 -c "import sys, json; print(json.load(sys.stdin)['github_secret_name_spn_secret'])")
        github_secret_name_spn_object_id=$(echo $file_content | python3 -c "import sys, json; print(json.load(sys.stdin)['github_secret_name_spn_object_id'])")
        github_secret_name_spn_id=$(echo $file_content | python3 -c "import sys, json; print(json.load(sys.stdin)['github_secret_name_spn_id'])")
        github_secret_name_subscription_id=$(echo $file_content | python3 -c "import sys, json; print(json.load(sys.stdin)['github_secret_name_subscription_id'])")
        
        echo "RESOURCE_GROUP_NAME=${resource_group_name}" >> $GITHUB_ENV
        echo "ENV_NAME=${env_name}" >> $GITHUB_ENV
        echo "ORGANISATION_NAME=${organisation_name}" >> $GITHUB_ENV
        echo "GITHUB_SECRET_NAME_SPN_SECRET=${github_secret_name_spn_secret}" >> $GITHUB_ENV
        echo "GITHUB_SECRET_NAME_SPN_OBJECT_ID=${github_secret_name_spn_object_id}" >> $GITHUB_ENV
        echo "GITHUB_SECRET_NAME_SPN_ID=${github_secret_name_spn_id}" >> $GITHUB_ENV
        echo "GITHUB_SECRET_NAME_SUBSCRIPTION_ID=${github_secret_name_subscription_id}" >> $GITHUB_ENV
      shell: bash